default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: video_help_dev
  username: postgres
  password: 5511josue

test:
  <<: *default
  database: video_help_test
  username: postgres
  password:

production:
  <<: *default
  database: video_help_production
  username: postgres
  password: 5511josue
